sim

diff --git a/.github/workflows/commit-author.yml b/.github/workflows/commit-author.yml
--- a/.github/workflows/commit-author.yml
+++ b/.github/workflows/commit-author.yml
@@ -1,41 +1,45 @@
 name: Commit Author CI
 
 on:
-  pull_request_review:
-  push:
+  pull_request:
 
 jobs:
-  check-approvals:
-    runs-on: ubuntu-latest
-    outputs:
-      result: ${{ steps.count_approvals.outputs.result }}
-    steps:
-      - id: count_approvals
-        run: |
-          echo "::set-output name=result::true"
-          MIN_APPROVALS_NEEDED=${{vars.MIN_APPROVALS_NEEDED}}
-          echo "$MIN_APPROVALS_NEEDED"
-          exit 0
   test:
     runs-on: ubuntu-latest
-    needs: check-approvals
-    if: needs.check-approvals.outputs.result == 'true'
-    timeout-minutes: 2
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      - uses: actions/checkout@v3
-
-      - name: "Run Test"
+      - uses: octokit/request-action@v2.x
+        id: get-commits
+        with:
+          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits
+      - name: "Checking commits authors email domain"
+        env:
+            COMMITS: ${{ steps.get-commits.outputs.data }}
         run: |
-          echo ${{ needs.check-approvals.outputs.result }}
-          echo "Hello, World!"
+          required_email_domain=${{ vars.EMAIL_DOMAIN }}
+          invalid_commits=0
+          for COMMIT in $(echo $COMMITS | jq -r '.[] | @base64'); do
+              _jq() {
+                echo ${COMMIT} | base64 --decode | jq -r ${1}
+              }
+              COMMIT_HASH=$(_jq '.sha')
+              COMMIT_MESSAGE=$(_jq '.commit.message')
+              COMMIT_AUTHOR=$(_jq '.commit.author.email')
+              
+              echo "Cheking commit: $COMMIT_HASH"
+              echo "    Commit message: \"$COMMIT_MESSAGE\""
+              author_email_domain=${COMMIT_AUTHOR#*@}
+              if [ $author_email_domain != $required_email_domain ]; then
+                  echo "    ❌ Invalid Author Email: $COMMIT_AUTHOR. Use a \`$required_email_domain\` domain email."
+                  echo "    See the commit here: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}/commits/$COMMIT_HASH"
+                  invalid_commits=$((invalid_commits+1))
+              else
+                  echo "    ✅ Valid Author Email: $COMMIT_AUTHOR"
+              fi
+          done
 
-  test2:
-    runs-on: ubuntu-latest
-    needs: test
-    timeout-minutes: 2
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: "Run Test"
-        run: |
-          echo "Hello, World!"
+          if [ $invalid_commits -gt 0 ]; then
+              exit 1
+          fi   
+ 
